### PR TITLE
Release v0.2.1

### PR DESCRIPTION
**Pull request by gfngfn**

### CODE REVIEW

**Comment by michallepicki** [comment]
I think it would be great if you could start attaching the built artifacts files to the github release. They are easier to discover for people that don't want to build from source. And these attachments don't expire like the github actions artifacts of commits.

This can be automated, together with specifying the release text based on changelog (I could work on that if you want), but for now you could download the aritifacts that are a result of github action on the tagged release commit, and manually upload when specifying release.

**Comment by michallepicki** [comment]
Or I can just start working on the automated release notes + artifact github action, so that it will magically happen for the next release.

**Comment by gfngfn** [comment]
> Or I can just start working on the automated release notes + artifact github action, so that it will magically happen for the next release

Thank you for the suggestion. Although for now I will release `v0.2.1` and attach the build artifacts to the release manually, it must be desirable for future releases to use such an automated procedure.

I would really appreciate it if you could work on that!

**Comment by michallepicki** [comment]
OK! Will work on that next.

**Pull request merged**
